#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require File.join(File.dirname(__FILE__), *%w[facebook_service])
require File.join(File.dirname(__FILE__), *%w[hive_metastore_types])

module ThriftHiveMetastore
  class Client < FacebookService::Client 
    include ::Thrift::Client

    def create_database(name, description)
      send_create_database(name, description)
      return recv_create_database()
    end

    def send_create_database(name, description)
      send_message('create_database', Create_database_args, :name => name, :description => description)
    end

    def recv_create_database()
      result = receive_message(Create_database_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'create_database failed: unknown result')
    end

    def get_database(name)
      send_get_database(name)
      return recv_get_database()
    end

    def send_get_database(name)
      send_message('get_database', Get_database_args, :name => name)
    end

    def recv_get_database()
      result = receive_message(Get_database_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_database failed: unknown result')
    end

    def drop_database(name)
      send_drop_database(name)
      return recv_drop_database()
    end

    def send_drop_database(name)
      send_message('drop_database', Drop_database_args, :name => name)
    end

    def recv_drop_database()
      result = receive_message(Drop_database_result)
      return result.success unless result.success.nil?
      raise result.o2 unless result.o2.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'drop_database failed: unknown result')
    end

    def get_databases()
      send_get_databases()
      return recv_get_databases()
    end

    def send_get_databases()
      send_message('get_databases', Get_databases_args)
    end

    def recv_get_databases()
      result = receive_message(Get_databases_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_databases failed: unknown result')
    end

    def get_type(name)
      send_get_type(name)
      return recv_get_type()
    end

    def send_get_type(name)
      send_message('get_type', Get_type_args, :name => name)
    end

    def recv_get_type()
      result = receive_message(Get_type_result)
      return result.success unless result.success.nil?
      raise result.o2 unless result.o2.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_type failed: unknown result')
    end

    def create_type(type)
      send_create_type(type)
      return recv_create_type()
    end

    def send_create_type(type)
      send_message('create_type', Create_type_args, :type => type)
    end

    def recv_create_type()
      result = receive_message(Create_type_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      raise result.o3 unless result.o3.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'create_type failed: unknown result')
    end

    def drop_type(type)
      send_drop_type(type)
      return recv_drop_type()
    end

    def send_drop_type(type)
      send_message('drop_type', Drop_type_args, :type => type)
    end

    def recv_drop_type()
      result = receive_message(Drop_type_result)
      return result.success unless result.success.nil?
      raise result.o2 unless result.o2.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'drop_type failed: unknown result')
    end

    def get_type_all(name)
      send_get_type_all(name)
      return recv_get_type_all()
    end

    def send_get_type_all(name)
      send_message('get_type_all', Get_type_all_args, :name => name)
    end

    def recv_get_type_all()
      result = receive_message(Get_type_all_result)
      return result.success unless result.success.nil?
      raise result.o2 unless result.o2.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_type_all failed: unknown result')
    end

    def get_fields(db_name, table_name)
      send_get_fields(db_name, table_name)
      return recv_get_fields()
    end

    def send_get_fields(db_name, table_name)
      send_message('get_fields', Get_fields_args, :db_name => db_name, :table_name => table_name)
    end

    def recv_get_fields()
      result = receive_message(Get_fields_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      raise result.o3 unless result.o3.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_fields failed: unknown result')
    end

    def get_schema(db_name, table_name)
      send_get_schema(db_name, table_name)
      return recv_get_schema()
    end

    def send_get_schema(db_name, table_name)
      send_message('get_schema', Get_schema_args, :db_name => db_name, :table_name => table_name)
    end

    def recv_get_schema()
      result = receive_message(Get_schema_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      raise result.o3 unless result.o3.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_schema failed: unknown result')
    end

    def create_table(tbl)
      send_create_table(tbl)
      recv_create_table()
    end

    def send_create_table(tbl)
      send_message('create_table', Create_table_args, :tbl => tbl)
    end

    def recv_create_table()
      result = receive_message(Create_table_result)
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      raise result.o3 unless result.o3.nil?
      raise result.o4 unless result.o4.nil?
      return
    end

    def drop_table(dbname, name, deleteData)
      send_drop_table(dbname, name, deleteData)
      recv_drop_table()
    end

    def send_drop_table(dbname, name, deleteData)
      send_message('drop_table', Drop_table_args, :dbname => dbname, :name => name, :deleteData => deleteData)
    end

    def recv_drop_table()
      result = receive_message(Drop_table_result)
      raise result.o1 unless result.o1.nil?
      raise result.o3 unless result.o3.nil?
      return
    end

    def get_tables(db_name, pattern)
      send_get_tables(db_name, pattern)
      return recv_get_tables()
    end

    def send_get_tables(db_name, pattern)
      send_message('get_tables', Get_tables_args, :db_name => db_name, :pattern => pattern)
    end

    def recv_get_tables()
      result = receive_message(Get_tables_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_tables failed: unknown result')
    end

    def get_table(dbname, tbl_name)
      send_get_table(dbname, tbl_name)
      return recv_get_table()
    end

    def send_get_table(dbname, tbl_name)
      send_message('get_table', Get_table_args, :dbname => dbname, :tbl_name => tbl_name)
    end

    def recv_get_table()
      result = receive_message(Get_table_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_table failed: unknown result')
    end

    def alter_table(dbname, tbl_name, new_tbl)
      send_alter_table(dbname, tbl_name, new_tbl)
      recv_alter_table()
    end

    def send_alter_table(dbname, tbl_name, new_tbl)
      send_message('alter_table', Alter_table_args, :dbname => dbname, :tbl_name => tbl_name, :new_tbl => new_tbl)
    end

    def recv_alter_table()
      result = receive_message(Alter_table_result)
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      return
    end

    def add_partition(new_part)
      send_add_partition(new_part)
      return recv_add_partition()
    end

    def send_add_partition(new_part)
      send_message('add_partition', Add_partition_args, :new_part => new_part)
    end

    def recv_add_partition()
      result = receive_message(Add_partition_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      raise result.o3 unless result.o3.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'add_partition failed: unknown result')
    end

    def append_partition(db_name, tbl_name, part_vals)
      send_append_partition(db_name, tbl_name, part_vals)
      return recv_append_partition()
    end

    def send_append_partition(db_name, tbl_name, part_vals)
      send_message('append_partition', Append_partition_args, :db_name => db_name, :tbl_name => tbl_name, :part_vals => part_vals)
    end

    def recv_append_partition()
      result = receive_message(Append_partition_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      raise result.o3 unless result.o3.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'append_partition failed: unknown result')
    end

    def drop_partition(db_name, tbl_name, part_vals, deleteData)
      send_drop_partition(db_name, tbl_name, part_vals, deleteData)
      return recv_drop_partition()
    end

    def send_drop_partition(db_name, tbl_name, part_vals, deleteData)
      send_message('drop_partition', Drop_partition_args, :db_name => db_name, :tbl_name => tbl_name, :part_vals => part_vals, :deleteData => deleteData)
    end

    def recv_drop_partition()
      result = receive_message(Drop_partition_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'drop_partition failed: unknown result')
    end

    def get_partition(db_name, tbl_name, part_vals)
      send_get_partition(db_name, tbl_name, part_vals)
      return recv_get_partition()
    end

    def send_get_partition(db_name, tbl_name, part_vals)
      send_message('get_partition', Get_partition_args, :db_name => db_name, :tbl_name => tbl_name, :part_vals => part_vals)
    end

    def recv_get_partition()
      result = receive_message(Get_partition_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_partition failed: unknown result')
    end

    def get_partitions(db_name, tbl_name, max_parts)
      send_get_partitions(db_name, tbl_name, max_parts)
      return recv_get_partitions()
    end

    def send_get_partitions(db_name, tbl_name, max_parts)
      send_message('get_partitions', Get_partitions_args, :db_name => db_name, :tbl_name => tbl_name, :max_parts => max_parts)
    end

    def recv_get_partitions()
      result = receive_message(Get_partitions_result)
      return result.success unless result.success.nil?
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_partitions failed: unknown result')
    end

    def get_partition_names(db_name, tbl_name, max_parts)
      send_get_partition_names(db_name, tbl_name, max_parts)
      return recv_get_partition_names()
    end

    def send_get_partition_names(db_name, tbl_name, max_parts)
      send_message('get_partition_names', Get_partition_names_args, :db_name => db_name, :tbl_name => tbl_name, :max_parts => max_parts)
    end

    def recv_get_partition_names()
      result = receive_message(Get_partition_names_result)
      return result.success unless result.success.nil?
      raise result.o2 unless result.o2.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_partition_names failed: unknown result')
    end

    def alter_partition(db_name, tbl_name, new_part)
      send_alter_partition(db_name, tbl_name, new_part)
      recv_alter_partition()
    end

    def send_alter_partition(db_name, tbl_name, new_part)
      send_message('alter_partition', Alter_partition_args, :db_name => db_name, :tbl_name => tbl_name, :new_part => new_part)
    end

    def recv_alter_partition()
      result = receive_message(Alter_partition_result)
      raise result.o1 unless result.o1.nil?
      raise result.o2 unless result.o2.nil?
      return
    end

  end

  class Processor < FacebookService::Processor 
    include ::Thrift::Processor

    def process_create_database(seqid, iprot, oprot)
      args = read_args(iprot, Create_database_args)
      result = Create_database_result.new()
      begin
        result.success = @handler.create_database(args.name, args.description)
      rescue AlreadyExistsException => o1
        result.o1 = o1
      rescue MetaException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'create_database', seqid)
    end

    def process_get_database(seqid, iprot, oprot)
      args = read_args(iprot, Get_database_args)
      result = Get_database_result.new()
      begin
        result.success = @handler.get_database(args.name)
      rescue NoSuchObjectException => o1
        result.o1 = o1
      rescue MetaException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'get_database', seqid)
    end

    def process_drop_database(seqid, iprot, oprot)
      args = read_args(iprot, Drop_database_args)
      result = Drop_database_result.new()
      begin
        result.success = @handler.drop_database(args.name)
      rescue MetaException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'drop_database', seqid)
    end

    def process_get_databases(seqid, iprot, oprot)
      args = read_args(iprot, Get_databases_args)
      result = Get_databases_result.new()
      begin
        result.success = @handler.get_databases()
      rescue MetaException => o1
        result.o1 = o1
      end
      write_result(result, oprot, 'get_databases', seqid)
    end

    def process_get_type(seqid, iprot, oprot)
      args = read_args(iprot, Get_type_args)
      result = Get_type_result.new()
      begin
        result.success = @handler.get_type(args.name)
      rescue MetaException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'get_type', seqid)
    end

    def process_create_type(seqid, iprot, oprot)
      args = read_args(iprot, Create_type_args)
      result = Create_type_result.new()
      begin
        result.success = @handler.create_type(args.type)
      rescue AlreadyExistsException => o1
        result.o1 = o1
      rescue InvalidObjectException => o2
        result.o2 = o2
      rescue MetaException => o3
        result.o3 = o3
      end
      write_result(result, oprot, 'create_type', seqid)
    end

    def process_drop_type(seqid, iprot, oprot)
      args = read_args(iprot, Drop_type_args)
      result = Drop_type_result.new()
      begin
        result.success = @handler.drop_type(args.type)
      rescue MetaException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'drop_type', seqid)
    end

    def process_get_type_all(seqid, iprot, oprot)
      args = read_args(iprot, Get_type_all_args)
      result = Get_type_all_result.new()
      begin
        result.success = @handler.get_type_all(args.name)
      rescue MetaException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'get_type_all', seqid)
    end

    def process_get_fields(seqid, iprot, oprot)
      args = read_args(iprot, Get_fields_args)
      result = Get_fields_result.new()
      begin
        result.success = @handler.get_fields(args.db_name, args.table_name)
      rescue MetaException => o1
        result.o1 = o1
      rescue UnknownTableException => o2
        result.o2 = o2
      rescue UnknownDBException => o3
        result.o3 = o3
      end
      write_result(result, oprot, 'get_fields', seqid)
    end

    def process_get_schema(seqid, iprot, oprot)
      args = read_args(iprot, Get_schema_args)
      result = Get_schema_result.new()
      begin
        result.success = @handler.get_schema(args.db_name, args.table_name)
      rescue MetaException => o1
        result.o1 = o1
      rescue UnknownTableException => o2
        result.o2 = o2
      rescue UnknownDBException => o3
        result.o3 = o3
      end
      write_result(result, oprot, 'get_schema', seqid)
    end

    def process_create_table(seqid, iprot, oprot)
      args = read_args(iprot, Create_table_args)
      result = Create_table_result.new()
      begin
        @handler.create_table(args.tbl)
      rescue AlreadyExistsException => o1
        result.o1 = o1
      rescue InvalidObjectException => o2
        result.o2 = o2
      rescue MetaException => o3
        result.o3 = o3
      rescue NoSuchObjectException => o4
        result.o4 = o4
      end
      write_result(result, oprot, 'create_table', seqid)
    end

    def process_drop_table(seqid, iprot, oprot)
      args = read_args(iprot, Drop_table_args)
      result = Drop_table_result.new()
      begin
        @handler.drop_table(args.dbname, args.name, args.deleteData)
      rescue NoSuchObjectException => o1
        result.o1 = o1
      rescue MetaException => o3
        result.o3 = o3
      end
      write_result(result, oprot, 'drop_table', seqid)
    end

    def process_get_tables(seqid, iprot, oprot)
      args = read_args(iprot, Get_tables_args)
      result = Get_tables_result.new()
      begin
        result.success = @handler.get_tables(args.db_name, args.pattern)
      rescue MetaException => o1
        result.o1 = o1
      end
      write_result(result, oprot, 'get_tables', seqid)
    end

    def process_get_table(seqid, iprot, oprot)
      args = read_args(iprot, Get_table_args)
      result = Get_table_result.new()
      begin
        result.success = @handler.get_table(args.dbname, args.tbl_name)
      rescue MetaException => o1
        result.o1 = o1
      rescue NoSuchObjectException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'get_table', seqid)
    end

    def process_alter_table(seqid, iprot, oprot)
      args = read_args(iprot, Alter_table_args)
      result = Alter_table_result.new()
      begin
        @handler.alter_table(args.dbname, args.tbl_name, args.new_tbl)
      rescue InvalidOperationException => o1
        result.o1 = o1
      rescue MetaException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'alter_table', seqid)
    end

    def process_add_partition(seqid, iprot, oprot)
      args = read_args(iprot, Add_partition_args)
      result = Add_partition_result.new()
      begin
        result.success = @handler.add_partition(args.new_part)
      rescue InvalidObjectException => o1
        result.o1 = o1
      rescue AlreadyExistsException => o2
        result.o2 = o2
      rescue MetaException => o3
        result.o3 = o3
      end
      write_result(result, oprot, 'add_partition', seqid)
    end

    def process_append_partition(seqid, iprot, oprot)
      args = read_args(iprot, Append_partition_args)
      result = Append_partition_result.new()
      begin
        result.success = @handler.append_partition(args.db_name, args.tbl_name, args.part_vals)
      rescue InvalidObjectException => o1
        result.o1 = o1
      rescue AlreadyExistsException => o2
        result.o2 = o2
      rescue MetaException => o3
        result.o3 = o3
      end
      write_result(result, oprot, 'append_partition', seqid)
    end

    def process_drop_partition(seqid, iprot, oprot)
      args = read_args(iprot, Drop_partition_args)
      result = Drop_partition_result.new()
      begin
        result.success = @handler.drop_partition(args.db_name, args.tbl_name, args.part_vals, args.deleteData)
      rescue NoSuchObjectException => o1
        result.o1 = o1
      rescue MetaException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'drop_partition', seqid)
    end

    def process_get_partition(seqid, iprot, oprot)
      args = read_args(iprot, Get_partition_args)
      result = Get_partition_result.new()
      begin
        result.success = @handler.get_partition(args.db_name, args.tbl_name, args.part_vals)
      rescue MetaException => o1
        result.o1 = o1
      end
      write_result(result, oprot, 'get_partition', seqid)
    end

    def process_get_partitions(seqid, iprot, oprot)
      args = read_args(iprot, Get_partitions_args)
      result = Get_partitions_result.new()
      begin
        result.success = @handler.get_partitions(args.db_name, args.tbl_name, args.max_parts)
      rescue NoSuchObjectException => o1
        result.o1 = o1
      rescue MetaException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'get_partitions', seqid)
    end

    def process_get_partition_names(seqid, iprot, oprot)
      args = read_args(iprot, Get_partition_names_args)
      result = Get_partition_names_result.new()
      begin
        result.success = @handler.get_partition_names(args.db_name, args.tbl_name, args.max_parts)
      rescue MetaException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'get_partition_names', seqid)
    end

    def process_alter_partition(seqid, iprot, oprot)
      args = read_args(iprot, Alter_partition_args)
      result = Alter_partition_result.new()
      begin
        @handler.alter_partition(args.db_name, args.tbl_name, args.new_part)
      rescue InvalidOperationException => o1
        result.o1 = o1
      rescue MetaException => o2
        result.o2 = o2
      end
      write_result(result, oprot, 'alter_partition', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Create_database_args
    include ::Thrift::Struct
    NAME = 1
    DESCRIPTION = 2

    ::Thrift::Struct.field_accessor self, :name, :description
    FIELDS = {
      NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
      DESCRIPTION => {:type => ::Thrift::Types::STRING, :name => 'description'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Create_database_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1
    O2 = 2

    ::Thrift::Struct.field_accessor self, :success, :o1, :o2
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::BOOL, :name => 'success'},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => AlreadyExistsException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_database_args
    include ::Thrift::Struct
    NAME = 1

    ::Thrift::Struct.field_accessor self, :name
    FIELDS = {
      NAME => {:type => ::Thrift::Types::STRING, :name => 'name'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_database_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1
    O2 = 2

    ::Thrift::Struct.field_accessor self, :success, :o1, :o2
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => Database},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => NoSuchObjectException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Drop_database_args
    include ::Thrift::Struct
    NAME = 1

    ::Thrift::Struct.field_accessor self, :name
    FIELDS = {
      NAME => {:type => ::Thrift::Types::STRING, :name => 'name'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Drop_database_result
    include ::Thrift::Struct
    SUCCESS = 0
    O2 = 2

    ::Thrift::Struct.field_accessor self, :success, :o2
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::BOOL, :name => 'success'},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_databases_args
    include ::Thrift::Struct

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_databases_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1

    ::Thrift::Struct.field_accessor self, :success, :o1
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRING}},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_type_args
    include ::Thrift::Struct
    NAME = 1

    ::Thrift::Struct.field_accessor self, :name
    FIELDS = {
      NAME => {:type => ::Thrift::Types::STRING, :name => 'name'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_type_result
    include ::Thrift::Struct
    SUCCESS = 0
    O2 = 1

    ::Thrift::Struct.field_accessor self, :success, :o2
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => Type},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Create_type_args
    include ::Thrift::Struct
    TYPE = 1

    ::Thrift::Struct.field_accessor self, :type
    FIELDS = {
      TYPE => {:type => ::Thrift::Types::STRUCT, :name => 'type', :class => Type}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Create_type_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1
    O2 = 2
    O3 = 3

    ::Thrift::Struct.field_accessor self, :success, :o1, :o2, :o3
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::BOOL, :name => 'success'},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => AlreadyExistsException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => InvalidObjectException},
      O3 => {:type => ::Thrift::Types::STRUCT, :name => 'o3', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Drop_type_args
    include ::Thrift::Struct
    TYPE = 1

    ::Thrift::Struct.field_accessor self, :type
    FIELDS = {
      TYPE => {:type => ::Thrift::Types::STRING, :name => 'type'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Drop_type_result
    include ::Thrift::Struct
    SUCCESS = 0
    O2 = 1

    ::Thrift::Struct.field_accessor self, :success, :o2
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::BOOL, :name => 'success'},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_type_all_args
    include ::Thrift::Struct
    NAME = 1

    ::Thrift::Struct.field_accessor self, :name
    FIELDS = {
      NAME => {:type => ::Thrift::Types::STRING, :name => 'name'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_type_all_result
    include ::Thrift::Struct
    SUCCESS = 0
    O2 = 1

    ::Thrift::Struct.field_accessor self, :success, :o2
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::MAP, :name => 'success', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::STRUCT, :class => Type}},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_fields_args
    include ::Thrift::Struct
    DB_NAME = 1
    TABLE_NAME = 2

    ::Thrift::Struct.field_accessor self, :db_name, :table_name
    FIELDS = {
      DB_NAME => {:type => ::Thrift::Types::STRING, :name => 'db_name'},
      TABLE_NAME => {:type => ::Thrift::Types::STRING, :name => 'table_name'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_fields_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1
    O2 = 2
    O3 = 3

    ::Thrift::Struct.field_accessor self, :success, :o1, :o2, :o3
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => FieldSchema}},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => MetaException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => UnknownTableException},
      O3 => {:type => ::Thrift::Types::STRUCT, :name => 'o3', :class => UnknownDBException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_schema_args
    include ::Thrift::Struct
    DB_NAME = 1
    TABLE_NAME = 2

    ::Thrift::Struct.field_accessor self, :db_name, :table_name
    FIELDS = {
      DB_NAME => {:type => ::Thrift::Types::STRING, :name => 'db_name'},
      TABLE_NAME => {:type => ::Thrift::Types::STRING, :name => 'table_name'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_schema_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1
    O2 = 2
    O3 = 3

    ::Thrift::Struct.field_accessor self, :success, :o1, :o2, :o3
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => FieldSchema}},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => MetaException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => UnknownTableException},
      O3 => {:type => ::Thrift::Types::STRUCT, :name => 'o3', :class => UnknownDBException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Create_table_args
    include ::Thrift::Struct
    TBL = 1

    ::Thrift::Struct.field_accessor self, :tbl
    FIELDS = {
      TBL => {:type => ::Thrift::Types::STRUCT, :name => 'tbl', :class => Table}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Create_table_result
    include ::Thrift::Struct
    O1 = 1
    O2 = 2
    O3 = 3
    O4 = 4

    ::Thrift::Struct.field_accessor self, :o1, :o2, :o3, :o4
    FIELDS = {
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => AlreadyExistsException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => InvalidObjectException},
      O3 => {:type => ::Thrift::Types::STRUCT, :name => 'o3', :class => MetaException},
      O4 => {:type => ::Thrift::Types::STRUCT, :name => 'o4', :class => NoSuchObjectException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Drop_table_args
    include ::Thrift::Struct
    DBNAME = 1
    NAME = 2
    DELETEDATA = 3

    ::Thrift::Struct.field_accessor self, :dbname, :name, :deleteData
    FIELDS = {
      DBNAME => {:type => ::Thrift::Types::STRING, :name => 'dbname'},
      NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
      DELETEDATA => {:type => ::Thrift::Types::BOOL, :name => 'deleteData'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Drop_table_result
    include ::Thrift::Struct
    O1 = 1
    O3 = 2

    ::Thrift::Struct.field_accessor self, :o1, :o3
    FIELDS = {
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => NoSuchObjectException},
      O3 => {:type => ::Thrift::Types::STRUCT, :name => 'o3', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_tables_args
    include ::Thrift::Struct
    DB_NAME = 1
    PATTERN = 2

    ::Thrift::Struct.field_accessor self, :db_name, :pattern
    FIELDS = {
      DB_NAME => {:type => ::Thrift::Types::STRING, :name => 'db_name'},
      PATTERN => {:type => ::Thrift::Types::STRING, :name => 'pattern'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_tables_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1

    ::Thrift::Struct.field_accessor self, :success, :o1
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRING}},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_table_args
    include ::Thrift::Struct
    DBNAME = 1
    TBL_NAME = 2

    ::Thrift::Struct.field_accessor self, :dbname, :tbl_name
    FIELDS = {
      DBNAME => {:type => ::Thrift::Types::STRING, :name => 'dbname'},
      TBL_NAME => {:type => ::Thrift::Types::STRING, :name => 'tbl_name'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_table_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1
    O2 = 2

    ::Thrift::Struct.field_accessor self, :success, :o1, :o2
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => Table},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => MetaException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => NoSuchObjectException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Alter_table_args
    include ::Thrift::Struct
    DBNAME = 1
    TBL_NAME = 2
    NEW_TBL = 3

    ::Thrift::Struct.field_accessor self, :dbname, :tbl_name, :new_tbl
    FIELDS = {
      DBNAME => {:type => ::Thrift::Types::STRING, :name => 'dbname'},
      TBL_NAME => {:type => ::Thrift::Types::STRING, :name => 'tbl_name'},
      NEW_TBL => {:type => ::Thrift::Types::STRUCT, :name => 'new_tbl', :class => Table}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Alter_table_result
    include ::Thrift::Struct
    O1 = 1
    O2 = 2

    ::Thrift::Struct.field_accessor self, :o1, :o2
    FIELDS = {
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => InvalidOperationException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Add_partition_args
    include ::Thrift::Struct
    NEW_PART = 1

    ::Thrift::Struct.field_accessor self, :new_part
    FIELDS = {
      NEW_PART => {:type => ::Thrift::Types::STRUCT, :name => 'new_part', :class => Partition}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Add_partition_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1
    O2 = 2
    O3 = 3

    ::Thrift::Struct.field_accessor self, :success, :o1, :o2, :o3
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => Partition},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => InvalidObjectException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => AlreadyExistsException},
      O3 => {:type => ::Thrift::Types::STRUCT, :name => 'o3', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Append_partition_args
    include ::Thrift::Struct
    DB_NAME = 1
    TBL_NAME = 2
    PART_VALS = 3

    ::Thrift::Struct.field_accessor self, :db_name, :tbl_name, :part_vals
    FIELDS = {
      DB_NAME => {:type => ::Thrift::Types::STRING, :name => 'db_name'},
      TBL_NAME => {:type => ::Thrift::Types::STRING, :name => 'tbl_name'},
      PART_VALS => {:type => ::Thrift::Types::LIST, :name => 'part_vals', :element => {:type => ::Thrift::Types::STRING}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Append_partition_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1
    O2 = 2
    O3 = 3

    ::Thrift::Struct.field_accessor self, :success, :o1, :o2, :o3
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => Partition},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => InvalidObjectException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => AlreadyExistsException},
      O3 => {:type => ::Thrift::Types::STRUCT, :name => 'o3', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Drop_partition_args
    include ::Thrift::Struct
    DB_NAME = 1
    TBL_NAME = 2
    PART_VALS = 3
    DELETEDATA = 4

    ::Thrift::Struct.field_accessor self, :db_name, :tbl_name, :part_vals, :deleteData
    FIELDS = {
      DB_NAME => {:type => ::Thrift::Types::STRING, :name => 'db_name'},
      TBL_NAME => {:type => ::Thrift::Types::STRING, :name => 'tbl_name'},
      PART_VALS => {:type => ::Thrift::Types::LIST, :name => 'part_vals', :element => {:type => ::Thrift::Types::STRING}},
      DELETEDATA => {:type => ::Thrift::Types::BOOL, :name => 'deleteData'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Drop_partition_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1
    O2 = 2

    ::Thrift::Struct.field_accessor self, :success, :o1, :o2
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::BOOL, :name => 'success'},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => NoSuchObjectException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_partition_args
    include ::Thrift::Struct
    DB_NAME = 1
    TBL_NAME = 2
    PART_VALS = 3

    ::Thrift::Struct.field_accessor self, :db_name, :tbl_name, :part_vals
    FIELDS = {
      DB_NAME => {:type => ::Thrift::Types::STRING, :name => 'db_name'},
      TBL_NAME => {:type => ::Thrift::Types::STRING, :name => 'tbl_name'},
      PART_VALS => {:type => ::Thrift::Types::LIST, :name => 'part_vals', :element => {:type => ::Thrift::Types::STRING}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_partition_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1

    ::Thrift::Struct.field_accessor self, :success, :o1
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => Partition},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_partitions_args
    include ::Thrift::Struct
    DB_NAME = 1
    TBL_NAME = 2
    MAX_PARTS = 3

    ::Thrift::Struct.field_accessor self, :db_name, :tbl_name, :max_parts
    FIELDS = {
      DB_NAME => {:type => ::Thrift::Types::STRING, :name => 'db_name'},
      TBL_NAME => {:type => ::Thrift::Types::STRING, :name => 'tbl_name'},
      MAX_PARTS => {:type => ::Thrift::Types::I16, :name => 'max_parts', :default => -1}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_partitions_result
    include ::Thrift::Struct
    SUCCESS = 0
    O1 = 1
    O2 = 2

    ::Thrift::Struct.field_accessor self, :success, :o1, :o2
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => Partition}},
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => NoSuchObjectException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_partition_names_args
    include ::Thrift::Struct
    DB_NAME = 1
    TBL_NAME = 2
    MAX_PARTS = 3

    ::Thrift::Struct.field_accessor self, :db_name, :tbl_name, :max_parts
    FIELDS = {
      DB_NAME => {:type => ::Thrift::Types::STRING, :name => 'db_name'},
      TBL_NAME => {:type => ::Thrift::Types::STRING, :name => 'tbl_name'},
      MAX_PARTS => {:type => ::Thrift::Types::I16, :name => 'max_parts', :default => -1}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_partition_names_result
    include ::Thrift::Struct
    SUCCESS = 0
    O2 = 1

    ::Thrift::Struct.field_accessor self, :success, :o2
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRING}},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Alter_partition_args
    include ::Thrift::Struct
    DB_NAME = 1
    TBL_NAME = 2
    NEW_PART = 3

    ::Thrift::Struct.field_accessor self, :db_name, :tbl_name, :new_part
    FIELDS = {
      DB_NAME => {:type => ::Thrift::Types::STRING, :name => 'db_name'},
      TBL_NAME => {:type => ::Thrift::Types::STRING, :name => 'tbl_name'},
      NEW_PART => {:type => ::Thrift::Types::STRUCT, :name => 'new_part', :class => Partition}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Alter_partition_result
    include ::Thrift::Struct
    O1 = 1
    O2 = 2

    ::Thrift::Struct.field_accessor self, :o1, :o2
    FIELDS = {
      O1 => {:type => ::Thrift::Types::STRUCT, :name => 'o1', :class => InvalidOperationException},
      O2 => {:type => ::Thrift::Types::STRUCT, :name => 'o2', :class => MetaException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

end

